### ISSUE TITLE
zotero更新到6.0.22之后，大部分功能都失效了

### ISSUE THREAD

**Issue by Paradox315** [zibrr/zotero-if-pro-max_cracked#19]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/56352258/222884600-503d8e82-93ed-4894-b29a-a72d6f5af17f.png">
<img width="825" alt="image" src="https://user-images.githubusercontent.com/56352258/222884606-d198d8fa-6435-431b-91bc-39fe3763da5a.png">
在控制台看到了这些报错

**Comment by uixiy** [comment]
hello, 请问你这个问题是解决了吗？
我也碰到这个问题，然后 zoteroif 所有按钮都不见了，使用 [这段 JavaScript 代码](https://github.com/zibrr/zotero-if-pro-max_cracked/issues/11#issuecomment-1323869102)也没解决。
